//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMArt.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PicturesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PicturesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMArt.Web.Resources.PicturesResources", typeof(PicturesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags:.
        /// </summary>
        public static string AddTagsLabel {
            get {
                return ResourceManager.GetString("AddTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        public static string AdvancedSearchLinkText {
            get {
                return ResourceManager.GetString("AdvancedSearchLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Max Rating.
        /// </summary>
        public static string ChangeMaxRatingPageTitle {
            get {
                return ResourceManager.GetString("ChangeMaxRatingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сomment:.
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CommentsSectionTitle {
            get {
                return ResourceManager.GetString("CommentsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        public static string DeselectAllButtonText {
            get {
                return ResourceManager.GetString("DeselectAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change.
        /// </summary>
        public static string DoNotChange {
            get {
                return ResourceManager.GetString("DoNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditFormTitle {
            get {
                return ResourceManager.GetString("EditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from search.
        /// </summary>
        public static string ExcludeTagHint {
            get {
                return ResourceManager.GetString("ExcludeTagHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string FavoriteButtonText {
            get {
                return ResourceManager.GetString("FavoriteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to search.
        /// </summary>
        public static string IncludeTagHint {
            get {
                return ResourceManager.GetString("IncludeTagHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max rating.
        /// </summary>
        public static string MaxRating {
            get {
                return ResourceManager.GetString("MaxRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string MetadataFileSize {
            get {
                return ResourceManager.GetString("MetadataFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string MetadataFormat {
            get {
                return ResourceManager.GetString("MetadataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MetadataPanelTitle {
            get {
                return ResourceManager.GetString("MetadataPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string MetadataResolution {
            get {
                return ResourceManager.GetString("MetadataResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:.
        /// </summary>
        public static string MetadataScore {
            get {
                return ResourceManager.GetString("MetadataScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string MetadataSource {
            get {
                return ResourceManager.GetString("MetadataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        public static string MetadataTags {
            get {
                return ResourceManager.GetString("MetadataTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded:.
        /// </summary>
        public static string MetadataUploaded {
            get {
                return ResourceManager.GetString("MetadataUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results for your query..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string OrientationAny {
            get {
                return ResourceManager.GetString("OrientationAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string OrientationLandscape {
            get {
                return ResourceManager.GetString("OrientationLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string OrientationPortrait {
            get {
                return ResourceManager.GetString("OrientationPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string OrientationSquare {
            get {
                return ResourceManager.GetString("OrientationSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture is declined by moderator..
        /// </summary>
        public static string PictureDeclinedModerationMessage {
            get {
                return ResourceManager.GetString("PictureDeclinedModerationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture not exists..
        /// </summary>
        public static string PictureNotExistsMessage {
            get {
                return ResourceManager.GetString("PictureNotExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture is awaiting moderation..
        /// </summary>
        public static string PicturePendingModerationMessage {
            get {
                return ResourceManager.GetString("PicturePendingModerationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string PrevButtonText {
            get {
                return ResourceManager.GetString("PrevButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not rated.
        /// </summary>
        public static string Rate0 {
            get {
                return ResourceManager.GetString("Rate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1.
        /// </summary>
        public static string Rate1 {
            get {
                return ResourceManager.GetString("Rate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2.
        /// </summary>
        public static string Rate2 {
            get {
                return ResourceManager.GetString("Rate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3.
        /// </summary>
        public static string Rate3 {
            get {
                return ResourceManager.GetString("Rate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string RatesDateColumnName {
            get {
                return ResourceManager.GetString("RatesDateColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        public static string RatesPageTitle {
            get {
                return ResourceManager.GetString("RatesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string RatesPictureColumnName {
            get {
                return ResourceManager.GetString("RatesPictureColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string RatesScoreColumnName {
            get {
                return ResourceManager.GetString("RatesScoreColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string RatesUserColumnName {
            get {
                return ResourceManager.GetString("RatesUserColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-15.
        /// </summary>
        public static string RatingR15 {
            get {
                return ResourceManager.GetString("RatingR15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-18.
        /// </summary>
        public static string RatingR18 {
            get {
                return ResourceManager.GetString("RatingR18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-18G.
        /// </summary>
        public static string RatingR18G {
            get {
                return ResourceManager.GetString("RatingR18G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFW.
        /// </summary>
        public static string RatingSFW {
            get {
                return ResourceManager.GetString("RatingSFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrated.
        /// </summary>
        public static string RatingUnrated {
            get {
                return ResourceManager.GetString("RatingUnrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string RelatedTagsTitle {
            get {
                return ResourceManager.GetString("RelatedTagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tags:.
        /// </summary>
        public static string RemoveTagsLabel {
            get {
                return ResourceManager.GetString("RemoveTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not tagged.
        /// </summary>
        public static string SatusTagme {
            get {
                return ResourceManager.GetString("SatusTagme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search query.
        /// </summary>
        public static string SearchBoxHint {
            get {
                return ResourceManager.GetString("SearchBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with.
        /// </summary>
        public static string SearchWith {
            get {
                return ResourceManager.GetString("SearchWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAllButtonText {
            get {
                return ResourceManager.GetString("SelectAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string SelectModeButtonText {
            get {
                return ResourceManager.GetString("SelectModeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set rating:.
        /// </summary>
        public static string SetRatingLabel {
            get {
                return ResourceManager.GetString("SetRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set source:.
        /// </summary>
        public static string SetSourceLabel {
            get {
                return ResourceManager.GetString("SetSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set status:.
        /// </summary>
        public static string SetStatusLabel {
            get {
                return ResourceManager.GetString("SetStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct link:.
        /// </summary>
        public static string ShareDirectLinkLabel {
            get {
                return ResourceManager.GetString("ShareDirectLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link:.
        /// </summary>
        public static string ShareViewerLinkLabel {
            get {
                return ResourceManager.GetString("ShareViewerLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share with.
        /// </summary>
        public static string ShareWith {
            get {
                return ResourceManager.GetString("ShareWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show unrated.
        /// </summary>
        public static string ShowUnrated {
            get {
                return ResourceManager.GetString("ShowUnrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Pictures.
        /// </summary>
        public static string SimilarPicturesSectionTitle {
            get {
                return ResourceManager.GetString("SimilarPicturesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortingBoxHint {
            get {
                return ResourceManager.GetString("SortingBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest resolution.
        /// </summary>
        public static string SortingHighestResolution {
            get {
                return ResourceManager.GetString("SortingHighestResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest resolution.
        /// </summary>
        public static string SortingLowestResolution {
            get {
                return ResourceManager.GetString("SortingLowestResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string SortingNewest {
            get {
                return ResourceManager.GetString("SortingNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string SortingOldest {
            get {
                return ResourceManager.GetString("SortingOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string SortingRandom {
            get {
                return ResourceManager.GetString("SortingRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top rated.
        /// </summary>
        public static string SortingTopRated {
            get {
                return ResourceManager.GetString("SortingTopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string StatusAccepted {
            get {
                return ResourceManager.GetString("StatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string StatusAny {
            get {
                return ResourceManager.GetString("StatusAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string StatusDeclined {
            get {
                return ResourceManager.GetString("StatusDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags string too long..
        /// </summary>
        public static string TagsStringTooLongMessage {
            get {
                return ResourceManager.GetString("TagsStringTooLongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsTitle {
            get {
                return ResourceManager.GetString("TagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string UploadedBy {
            get {
                return ResourceManager.GetString("UploadedBy", resourceCulture);
            }
        }
    }
}
