//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMArt.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMArt.Web.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to top.
        /// </summary>
        public static string BackToTop {
            get {
                return ResourceManager.GetString("BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ButtonDetails {
            get {
                return ResourceManager.GetString("ButtonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not need to enter a captcha, if you are logged in..
        /// </summary>
        public static string CaptchaForAuthenticated {
            get {
                return ResourceManager.GetString("CaptchaForAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string CaptchaLabel {
            get {
                return ResourceManager.GetString("CaptchaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes were successfully saved..
        /// </summary>
        public static string ChangesSuccessfullySavedMessage {
            get {
                return ResourceManager.GetString("ChangesSuccessfullySavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid captcha..
        /// </summary>
        public static string InvalidCaptchaMessage {
            get {
                return ResourceManager.GetString("InvalidCaptchaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MenuAccount {
            get {
                return ResourceManager.GetString("MenuAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administer.
        /// </summary>
        public static string MenuAdminister {
            get {
                return ResourceManager.GetString("MenuAdminister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string MenuChangeLocale {
            get {
                return ResourceManager.GetString("MenuChangeLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussions.
        /// </summary>
        public static string MenuDiscussions {
            get {
                return ResourceManager.GetString("MenuDiscussions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string MenuFavorites {
            get {
                return ResourceManager.GetString("MenuFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string MenuFeedback {
            get {
                return ResourceManager.GetString("MenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string MenuHistory {
            get {
                return ResourceManager.GetString("MenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string MenuLogIn {
            get {
                return ResourceManager.GetString("MenuLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string MenuRandom {
            get {
                return ResourceManager.GetString("MenuRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string MenuRecent {
            get {
                return ResourceManager.GetString("MenuRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string MenuRegistration {
            get {
                return ResourceManager.GetString("MenuRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string MenuTags {
            get {
                return ResourceManager.GetString("MenuTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string MenuTerms {
            get {
                return ResourceManager.GetString("MenuTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Rated.
        /// </summary>
        public static string MenuTopRated {
            get {
                return ResourceManager.GetString("MenuTopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string MenuUpload {
            get {
                return ResourceManager.GetString("MenuUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextRandom {
            get {
                return ResourceManager.GetString("NextRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ObjectMessage {
            get {
                return ResourceManager.GetString("ObjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string ObjectPicture {
            get {
                return ResourceManager.GetString("ObjectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string ObjectTag {
            get {
                return ResourceManager.GetString("ObjectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PagingNext {
            get {
                return ResourceManager.GetString("PagingNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string PagingPrev {
            get {
                return ResourceManager.GetString("PagingPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and try again..
        /// </summary>
        public static string UnsuccessfulOperationMessage {
            get {
                return ResourceManager.GetString("UnsuccessfulOperationMessage", resourceCulture);
            }
        }
    }
}
