//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMArt.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TagsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TagsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMArt.Web.Resources.TagsResources", typeof(TagsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string AliasesField {
            get {
                return ResourceManager.GetString("AliasesField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Childs.
        /// </summary>
        public static string ChildsField {
            get {
                return ResourceManager.GetString("ChildsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Cloud.
        /// </summary>
        public static string CloudPageTitle {
            get {
                return ResourceManager.GetString("CloudPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string CountField {
            get {
                return ResourceManager.GetString("CountField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag is declined by moderator..
        /// </summary>
        public static string DeclinedModerationMessage {
            get {
                return ResourceManager.GetString("DeclinedModerationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tags: {0}.
        /// </summary>
        public static string InvalidTagsMessage {
            get {
                return ResourceManager.GetString("InvalidTagsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameField {
            get {
                return ResourceManager.GetString("NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        public static string ParentsField {
            get {
                return ResourceManager.GetString("ParentsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag is awaiting moderation..
        /// </summary>
        public static string PendingModerationMessage {
            get {
                return ResourceManager.GetString("PendingModerationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string SortByLabel {
            get {
                return ResourceManager.GetString("SortByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least used.
        /// </summary>
        public static string SortOrderLeastUsed {
            get {
                return ResourceManager.GetString("SortOrderLeastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most used.
        /// </summary>
        public static string SortOrderMostUsed {
            get {
                return ResourceManager.GetString("SortOrderMostUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (A-Z).
        /// </summary>
        public static string SortOrderNameAsc {
            get {
                return ResourceManager.GetString("SortOrderNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Z-A).
        /// </summary>
        public static string SortOrderNameDesc {
            get {
                return ResourceManager.GetString("SortOrderNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string SortOrderNewest {
            get {
                return ResourceManager.GetString("SortOrderNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string SortOrderOldest {
            get {
                return ResourceManager.GetString("SortOrderOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string TypeAny {
            get {
                return ResourceManager.GetString("TypeAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string TypeArtist {
            get {
                return ResourceManager.GetString("TypeArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string TypeCharacter {
            get {
                return ResourceManager.GetString("TypeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string TypeCopyright {
            get {
                return ResourceManager.GetString("TypeCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeField {
            get {
                return ResourceManager.GetString("TypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TypeGeneral {
            get {
                return ResourceManager.GetString("TypeGeneral", resourceCulture);
            }
        }
    }
}
